### ISSUE TITLE
请教，在命令行环境下如何配置、运行xray？

### ISSUE THREAD

**Issue by shermanx** [yichya/openwrt-xray#11]
硬件是一部ISP高度定制的openwrt路由器，无法安装luci，已经成功装上Xray 1.5.8 apk，cpu是ARMv7 Processor rev 1 (v7l)双核, 512内存。

请问如何配置分流、下载geodata和运行xray？有没有命令行下的基本教程及配置文件的样本？

谢谢!

**Comment by yichya** [comment]
没有 luci 的话试试再装个 [v2raya](https://github.com/openwrt/packages/tree/master/net/v2raya)

**Comment by shermanx** [comment]
多谢回复，没找到apk包，这个是要clone下来自编译吗？

**Comment by yichya** [comment]
> 多谢回复，没找到apk包，这个是要clone下来自编译吗？

可以在官方的 opkg 仓库找一下你的 architecture 对应的包，比如 [x86_64](https://downloads.openwrt.org/snapshots/packages/x86_64/packages/v2raya_1.5.8.1-1_x86_64.ipk)

**Comment by shermanx** [comment]
参考文件

**Comment by shermanx** [comment]
参考文件弄好了，但是有个log的问题请教：
config里面如何配置，才能让access.log里面显示域名、而不是ip？我加了"dnsLog": true，但是只是有很多DNS UDP HIT：
比如我想让下面第三行显示domain name，应该如何做？谢谢！

2022/07/11 17:35:56 UDP:8.8.8.8:53 cache HIT: connectivitycheck.gstatic.com -> [172.217.24.35]
2022/07/11 17:35:56 UDP:8.8.8.8:53 cache HIT: connectivitycheck.gstatic.com -> [172.217.24.35]
**2022/07/11 17:36:00 192.168.10.176:54237 accepted tcp:203.205.235.132:80 [DIR]**
2022/07/11 17:36:00 UDP:8.8.8.8:53 cache HIT: szextshort.weixin.qq.com -> [203.205.254.25, 203.205.235.132]
2022/07/11 17:36:05 UDP:8.8.8.8:53 cache HIT: szminorshort.weixin.qq.com -> [203.205.219.56, 203.205.232.101]
2022/07/11 17:36:08 UDP:8.8.8.8:53 cache HIT: szextshort.weixin.qq.com -> [203.205.254.25, 203.205.235.132]
2022/07/11 17:36:10 UDP:8.8.8.8:53 cache HIT: tv6.aiseet.atianqi.com -> [129.226.107.233, 129.226.107.253]

**Comment by yichya** [comment]
> config里面如何配置，才能让access.log里面显示域名、而不是ip？

透明代理的场景下

* 开 sniffing，但可能有些其他影响
* 不借助 sniffing 的话做不到，因为从 tproxy 进来的时候就没有域名

**Comment by shermanx** [comment]
已经开了：没加错地方吧？

"inbounds": [
		{
			"port": "1080",
			"protocol": "socks",
			"settings": {
				"auth": "noauth",
				"udp": true
			},
			"tag": "in-0"
		},
		{
			"port": "1081",
			"protocol": "http",
			"settings": {},
			"tag": "in-1"
		},
		{
			"port": 12315,
			"protocol": "dokodemo-door",
			"settings": {
				"network": "tcp,udp",
				"followRedirect": true
			},
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			},
			"streamSettings": {
				"sockopt": {
					"tproxy": "redirect"
				}
			}
		}
	],
