### ISSUE TITLE
请教编译mipsel的xray内核

### ISSUE THREAD

**Issue by nameup2** [yichya/openwrt-xray#3]
你好我在网上找了很久都没有我可以安装的mipsel_1004kc_dsp 的xray内核，有幸找到了你的仓库，想问下如果我把你的这个仓库fork到我的仓库，然后改下面的- arch: mipsel_24kc 变成mipsel_1004kc_dsp
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/ramips/mt7620   7620改成7621
            sdk_name: -sdk-ramips-mt7620_改成7621.
这样的方式后进入action编译，会成功编出来mipsel_1004kc_dsp的xray内核吗？

**Comment by nameup2** [comment]
如果可以的话能您能实验性的加上arch: mipsel_1004kc_dsp看下能编译出xray内核吗？我的路由器cpu只能安装1004kc的内核，因为固件比较久远，网上找了很多的文章和信息都没找到关于如何编译1004kc内核的线索，

**Comment by yichya** [comment]
具体是啥设备。我看下怎么配置 sdk

**Comment by nameup2** [comment]
万分感谢回复，我的设备是PandoraBox-ralink-mt7621-newifi3-d2，插件用的是mipsel_1004kc_dsp.ipk其他的都打不上

**Comment by yichya** [comment]
你直接拿这种 mipsel24kc 的二进制文件运行能跑起来嘛

**Comment by nameup2** [comment]
我i试过了，打不进去，这个newifi3的cpu很怪，本来mipsel24kc是通用的mt7621通用的，这个非得是1004kc的，很无语，我这边也在尽力学编译，无奈基础不行，我fork了lean的仓库想用网上教的编译办法用git checkout查找一个历史版本都不会，太难了，

**Comment by yichya** [comment]
ipk 说白了是一个压缩包，拿 7z 什么的打开，双击进去找 data.tar.gz，再进去找 usr/bin/xray，然后把这个直接拖到你的路由器上当一个命令运行能起得来嘛

**Comment by nameup2** [comment]
我试过了这种方式，下载后替换了原来在路由的usr/bin/xray，完成后直接ssrplus直接开不起来。试过了添加修改opkg
overlay的arch100，mipsel24kc 200，这样的命令都无效

**Comment by nameup2** [comment]
大佬你看下，他这个内核是这样的一种方式固件https://www.right.com.cn/forum/thread-4071190-1-1.html
我还特地新开了一台ubuntu18的vps去做这个编译的事情，学的几个教程，特别是恩山这个朋友的教程，https://www.right.com.cn/forum/thread-4044875-1-1.html   所有都按步骤，最后就是编译失败- -！我现在感觉学这些东西没基础真的不行！

**Comment by libregratis** [comment]
> 万分感谢回复，我的设备是PandoraBox-ralink-mt7621-newifi3-d2，插件用的是mipsel_1004kc_dsp.ipk其他的都打不上

会不会是固件的原因？

手头有一台小米r3g上刷了openwrt官方固件19.07，再安装@kuoruan的openwrt-v2ray
用的就是v2ray-core_4.36.2-1_mipsel_24kc.ipk，搭配luci-app-v2ray，使用一切正常
不过openwrt-v2ray只支持vmess和shadowsocks，所以最近在r3g上折腾xray

刚刚在r3g上opkg install openwrt-xray_1.4.1-1_mipsel_24kc.ipk安装成功
还没来得及配置，就看见这个issue，提一个想法仅供参考

查了一下openwrt官网，小米r3g和新三d2用的都是MT7621AT，mipsel_24kc架构
既然小米r3g在openwrt官方固件可以opkg安装openwrt-xray
那么新三d2刷了openwrt官方估计后，理论上也是可以的
况且新三的bootloader还是不死breed

https://downloads.openwrt.org/releases/19.07.7/targets/ramips/mt7621/
https://openwrt.org/toh/hwdata/d-team/d-team_newifi_d2
https://openwrt.org/toh/hwdata/xiaomi/xiaomi_miwifi_3g

@yichya 请教一下大佬，看luci-app-xray的readme开头就提到
luci-app-v2ray refined to client side rendering (and switched to xray as well).
是否意味着在luci-app-v2ray里将v2ray flie和v2ray asset location指向xray的相关文件和目录就可以了？
是否和在qv2ray里将v2ray-core替换为xray-core类似？

**Comment by yichya** [comment]
> 是否意味着在luci-app-v2ray里将v2ray flie和v2ray asset location指向xray的相关文件和目录就可以了？

我之前用的那个 luci-app-v2ray 是好久好久之前的版本了，换自然是可以换的，但是 xray 值得用的功能怕是都不支持。。。

**Comment by libregratis** [comment]
> > 是否意味着在luci-app-v2ray里将v2ray flie和v2ray asset location指向xray的相关文件和目录就可以了？
> 
> 我之前用的那个 luci-app-v2ray 是好久好久之前的版本了，换自然是可以换的，但是 xray 值得用的功能怕是都不支持。。。

> 

- 

- [](url)

**Comment by libregratis** [comment]
> > > 是否意味着在luci-app-v2ray里将v2ray flie和v2ray asset location指向xray的相关文件和目录就可以了？
> > 
> > 
> > 我之前用的那个 luci-app-v2ray 是好久好久之前的版本了，换自然是可以换的，但是 xray 值得用的功能怕是都不支持。。。
> 
> > 
> 
> *
感谢，确实如此，只是简单把v2ray flie从v2ray指向xray，luci-app-v2ray已经正确显示xray运行和版本，各项访问也一切正常
![2021-04-02 03-32-10 的屏幕截图](https://user-images.githubusercontent.com/78979149/113345076-87d79f80-9364-11eb-8e10-e93da2a6c4c1.png)
但outbound里，add新节点依然没有vless
看来之前的想法太简单了，还是应该编译luci-app-xray，否则只能用cli了

**Comment by libregratis** [comment]
done
![2021-04-23 03-07-25 的屏幕截图](https://user-images.githubusercontent.com/78979149/115773909-7a518a80-a3e3-11eb-9e71-def50302bd2f.png)

thx

**Comment by v03413** [comment]
> 你好我在网上找了很久都没有我可以安装的mipsel_1004kc_dsp 的xray内核，有幸找到了你的仓库，想问下如果我把你的这个仓库fork到我的仓库，然后改下面的- arch: mipsel_24kc 变成mipsel_1004kc_dsp sdk_url_path: https://downloads.openwrt.org/snapshots/targets/ramips/mt7620 7620改成7621 sdk_name: -sdk-ramips-mt7620_改成7621. 这样的方式后进入action编译，会成功编出来mipsel_1004kc_dsp的xray内核吗？

我的红米ac2100也是 mt7621的 u，编译使用命令
```bash
GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -trimpath -ldflags "-s -w -buildid" -o xray ./main
```
直接编译最新`1.5.1`版本内核，亲测可运行，或许你可以试下。
<img width="528" alt="WX20211230-142734@2x" src="https://user-images.githubusercontent.com/49953737/147727177-40fd250d-c4ae-413c-9d23-be70be88bb2b.png">
