### ISSUE TITLE
可以更新发布1.4.5版本吗？

### ISSUE THREAD

**Issue by junmin** [yichya/openwrt-xray#5]
先谢谢你的编译！~ 1.4.2 一直用的挺愉快的
但是1.4.2的一个bug  https://github.com/XTLS/Xray-core/issues/383 妨碍了科学上网
在1.4.5更新过来了，如果可以的话，烦请更新一下，谢谢

**Comment by yichya** [comment]
1.4.5 是哪个分支。。。没见到这个 release 啊
