### ISSUE TITLE
用openwrt官方源码master分支编译openwrt-xray及luci-app-xray的问题

### ISSUE THREAD

**Issue by 13528943945** [yichya/openwrt-xray#8]
两个问题请教大佬！
问题一：
用openwrt官方源码master分支将版主的openwrt-xray及luci-app-xray两个git源添加进feeds.conf.default
src-git xraycore https://github.com/yichya/openwrt-xray.git
src-git xrayapp https://github.com/yichya/luci-app-xray.git
然后./scripts/feeds update -a，即出现如下提示！

Create index file './feeds/xraycore.index' 
grep: feeds/xraycore/Makefile:$(eval: 没有那个文件或目录
grep: $(call: 没有那个文件或目录
grep: BuildPackage,$(PKG_NAME)))/Makefile: 没有那个文件或目录
/home/lyh/openwrt/feeds/xraycore.tmp/info/.files-packageinfo.mk:1: *** 目标模式不含有“%”。 停止。
Collecting target info: done
Create index file './feeds/xrayapp.index' 
grep: feeds/xrayapp/Makefile:$(eval: 没有那个文件或目录
grep: $(call: 没有那个文件或目录
grep: BuildPackage,$(PKG_NAME)))/Makefile: 没有那个文件或目录
/home/lyh/openwrt/feeds/xrayapp.tmp/info/.files-packageinfo.mk:1: *** 目标模式不含有“%”。 停止。

问题二：openwrt官方源码master分支的packages里已经包含有xray-core包，是否兼容版主的luci-app-xray？

**Comment by yichya** [comment]
> 用openwrt官方源码master分支将版主的openwrt-xray及luci-app-xray两个git源添加进feeds.conf.default

这个不是这么用的，把这两个仓库直接 clone 到 `package/extra` 下面（没有就 `mkdir -p package/extra`）

> 问题二：openwrt官方源码master分支的packages里已经包含有xray-core包，是否兼容版主的luci-app-xray？

luci-app-xray 跟天灵的那个 xray-core 用的配置文件和 init 脚本文件都重名了，opkg 是肯定装不上 luci-app-xray 的，硬要这样用的话需要覆盖掉 xray-core 提供的这两个文件
