### ISSUE TITLE
大佬，xray运行文件提取出来，用了Loyalsoldier/v2ray-rules-dat的config.json提示找不到geoip.dat: !CN

### ISSUE THREAD

**Issue by fengchen-github** [yichya/openwrt-xray#9]
Xray 1.5.0 (Xray, Penetrates Everything.) Custom (go1.17.2 linux/mipsle)
A unified platform for anti-censorship.
2021/11/24 02:11:23 [Info] infra/conf/serial: Reading config: config.json
Failed to start: main: failed to load config files: [config.json] > infra/conf: failed to parse DNS config > infra/conf: failed to build na                                                      meserver > infra/conf: invalid IP rule: [geoip:!cn] > infra/conf: failed to load GeoIP: !cn > infra/conf: code not found in geoip.dat: !CN

如上错误，geoip.dat要放在什么指定目录吗

**Comment by yichya** [comment]
xray 目前应该还不支持 `!cn` 这种用法

**Comment by fengchen-github** [comment]
> xray 目前应该还不支持 `!cn` 这种用法

哦，谢谢大佬
